FROM lavasoftware/amd64-lava-dispatcher:2018.11

RUN apt-get update; exit 0
RUN dpkg --add-architecture i386 \
#RUN apt-get install -y emacs24 vim lavacli lxc fastboot sudo
&& apt-get install -y emacs24 vim lavacli lxc fastboot libusb-0.1-4 sudo


# Install android tools + sdk
ENV ANDROID_HOME /opt/android-sdk-linux
ENV PATH $PATH:${ANDROID_HOME}/tools:$ANDROID_HOME/platform-tools

# Set up insecure default key
RUN mkdir -m 0750 /.android
ADD adb/insecure_shared_adbkey /.android/adbkey
ADD adb/insecure_shared_adbkey.pub /.android/adbkey.pub

#RUN wget -qO- "http://dl.google.com/android/android-sdk_r24.3.4-linux.tgz" | tar -zx -C /opt && \
	    #echo y | android update sdk --no-ui --all --filter platform-tools --force

RUN mkdir -p /home/lava
RUN mkdir -p /opt/share
RUN mkdir -p /root/.config

COPY ./home-bin-slave /home/lava/bin
#COPY ./home /home
COPY ./LAVA-TEST /opt/share
COPY ./etc/ser2net.conf /etc/
#COPY ./etc/hostname.sh /etc/
COPY ./usr/lib/python3 /usr/lib/python3/
#COPY .bashrc /root/

EXPOSE 69 80 5555 5556

#RUN mkdir -p /var/lib/nexell

