FROM lavasoftware/amd64-lava-server:2018.11

RUN apt-get install -y vim lavacli

RUN mkdir -p /root/.config

COPY ./home-bin-server /home/lava/bin
COPY ./home /home

COPY ./etc /etc
#COPY ./usr /usr
#COPY .bashrc /root/

#RUN mkdir -p /var/lib/nexell

EXPOSE 69 80 5555 5556 5432 8000 5500
